version: "3"

services:
  nextcloud:
    image: "nextcloud:latest"
    restart: always
    ports:
      - "4321:80"
    # volumes:
    #   - 'nextcloud:/var/www/html/data'
    # command: 'chmod -R 770 /var/www/html/data'

  uptimekuma:
    image: elestio/uptime-kuma:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      - ServerIP=localhost
      - TZ=Europe/Rome

  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=mysqldocker
      - MYSQL_PASSWORD=mysqldockerpassword
      - MYSQL_ROOT_PASSWORD=mysqldockerrootpassword

  apache2:
    container_name: apache2
    image: "httpd:latest"
    ports:
      - 9001:9001
    restart: always

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  vaultwarden:
    container_name: storage-vaultwarden
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./vw-data:/data
    environment:
      - ROCKET_PORT=60
      - ROCKET_WORKERS=10
    ports:
      - "60:60"
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email marcopac.363.d@gmail.com -d solidyellow.ddns.net --agree-tos

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: "192.168.1.69" #update, assign open ip manually
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: "America/New_York" # update according to your timezone
      WEBPASSWORD: "choose secured password" #update password
    volumes:
      - "/home/username/pihole/etc-pihole:/etc/pihole" #update
      - "/home/username/pihole/etc-dnsmasq.d:/etc/dnsmasq.d" #update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  default:
    driver: bridge
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24 #update if needed
          gateway: 192.168.1.1 #update if needed

volumes:
  nextcloud:
  pihole:
  uptimekuma:
  certbot:
  apache2:
