version: '3'

services:
  nextcloud:
    image: 'nextcloud:latest'
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - '/mnt/nextcloud:/var/www/html'


  pihole:
    image: 'pihole/pihole'
    environment:
      - 'TZ=Europe/London'
      - 'WEBPASSWORD=yourpassword'
      - 'DNS1=8.8.8.8'


  uptimekuma:
    image: 'linuxserver/uptimekuma'
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
      - 'PORT=3000'



  certbot:
    image: 'certbot/certbot'
    command: 'certonly --webroot --webroot-path=/var/www/html --email'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'

  apache2:
    image: 'httpd:2.4'
    ports:
      - '80:80'
      - '443:443'
