version: "3"

services:
  nextcloud:
    image: "nextcloud:latest"
    restart: unless-stopped
    ports:
      - "4321:80"
    # volumes:
    #   - 'nextcloud:/var/www/html/data'
    # command: 'chmod -R 770 /var/www/html/data'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: "192.168.1.69" #update, assign open ip manually
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "5555:80/tcp"
    environment:
      TZ: "America/New_York" # update according to your timezone
      WEBPASSWORD: "choose secured password" #update password
    volumes:
      - "/home/username/pihole/etc-pihole:/etc/pihole" #update
      - "/home/username/pihole/etc-dnsmasq.d:/etc/dnsmasq.d" #update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  uptimekuma:
    image: elestio/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - ServerIP=localhost
      - TZ=Europe/Rome

  apache2:
    image: "httpd:latest"
    ports:
      - "80:80"
    restart: unless-stopped

  mysql:
    image: "mysql:latest"
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=mysqldocker
      - MYSQL_PASSWORD=mysqldockerpassword
      - MYSQL_ROOT_PASSWORD=mysqldockerrootpassword

volumes:
  nextcloud:
  pihole:
  uptimekuma:
  certbot:
  apache2:

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24 #update if needed
          gateway: 192.168.1.1 #update if needed
