version: '3'

services:
  nextcloud:
    image: 'nextcloud:latest'
    restart: always
    ports:
      - '4321:80'
    # volumes:
    #   - 'nextcloud:/var/www/html/data'
    # command: 'chmod -R 770 /var/www/html/data'


  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: always
    environment:
      - TZ=Europe/Rome
      - ServerIP=localhost #ip da cui si configura il pihole
      - WEBPASSWORD=piholedocker #da cambiare
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
    dns:
      - 127.0.0.1
      - solidyellow.ddns.net
    dns_search:
      - local
    ports:
      - "5555:80"
    cap_add:
      - NET_ADMIN


  uptimekuma:
    image: elestio/uptime-kuma:latest
    restart: always
    ports:
      - '3001:3001'
    environment:
      - ServerIP=localhost
      - TZ=Europe/Rome

  # certbot:
  #   image: 'certbot/certbot'
  #   command: 'certonly --webroot --webroot-path=/var/www/html --email'
  #   volumes:
  #     - '/etc/letsencrypt:/etc/letsencrypt'
  #   restart: always

  nginx:
    image: 'nginx:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../html:/usr/share/nginx/html'

volumes:
  nextcloud:
  pihole:
  uptimekuma:
  certbot:
  apache2:
  # postgresql:
  # mysql:
  # vpn:
