version: '3'

services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - helloworld

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email marcopac.363.d@gmail.com -d solidyellow.ddns.net --agree-tos




  # pivpn:
  #   image: pivpn/pivpn
  #   container_name: pivpn
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - "1194:1194/udp"
  #   environment:
  #     - SERVER_OVPN_DEFROUTE=false # Set to true if you want to route all client traffic through VPN
  #   volumes:
  #     - ./ovpndata:/home/pivpn/ovpndata
  #   stdin_open: true
  #   tty: true

